# version: '3'
# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/code
#     environment:
#       FLASK_ENV: development


version: "3.4"
services:
  python: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 aimvector/python:1.0.0 /bin/sh
    container_name: python
    image: aimvector/python:1.0.0
    build:
      context: reddit_twitter_data_api_with_sqlite
    #   target: debug
    build: ""
    volumes:
      - ./reddit_twitter_data_api_with_sqlite:/work
      # - ./Sources/:/work
    ports:
      - 5003:5000
      - 5678:5678
    environment:
      FLASK_ENV: development
